### ISSUE TITLE
Is this the right "url", or has something changed server-side?

### ISSUE THREAD

**Issue by ratkins** [Bouni/ard-mediathek#22]
```
$ pipenv run python ard-mediathek.py https://www.daserste.de/unterhaltung/serie/babylon-berlin/videos-extras/Babylon_Berlin_1-folge-100.html --derivefilename
Since no filename was given the default value 'video-folge-1-babylon-berlin-ard.mp4' will be used.
Traceback (most recent call last):
  File "ard-mediathek.py", line 37, in <module>
    main(sys.argv)
  File "ard-mediathek.py", line 30, in main
    amd.download()
  File "/Users/ratkins/workspace/ard-mediathek/ard_media_downloader.py", line 50, in download
    video_url = self.get_video_url()
  File "/Users/ratkins/workspace/ard-mediathek/ard_media_downloader.py", line 79, in get_video_url
    raise RuntimeError("The document id could not be found.")
RuntimeError: The document id could not be found.
```

The following URLs also get the same error:
```
http://mediathek.daserste.de/db801b47-182d-406f-b9f8-d1d272092f96
http://mediathek.daserste.de/Babylon-Berlin/Folge-1/Video?bcastId=54319834&documentId=59059580
```

**Comment by steffenschroeder** [comment]
Can you please try the url, which contains `documentId` (and put the URL in quotes): 
`pipenv run python ard-mediathek.py "http://mediathek.daserste.de/Babylon-Berlin/Folge-1/Video?bcastId=54319834&documentId=59059580" --derivefilename`

That worked for me

**Comment by ratkins** [comment]
Well there you go, I guess it was the quotes. Thanks.
