### ISSUE TITLE
RuntimeError: The document id could not be found

### ISSUE THREAD

**Issue by donfellone** [Bouni/ard-mediathek#24]
Hi,

I really like your project and wish it'd work for me, but i got an error, unfortunately:

python3 PATH/ard-mediathek.py "https://www.ardmediathek.de/ard/player/Y3JpZDovL3dkci5kZS9CZWl0cmFnLTk4ZDVjNDBlLWJkOTktNDg2YS05YTFiLTk2MGQ1M2UzNzNlZA/" --filename handball_test
Traceback (most recent call last):
  File "/Users/Downloads/ard-mediathek-master/ard-mediathek.py", line 37, in <module>
    main(sys.argv)
  File "/Users/Downloads/ard-mediathek-master/ard-mediathek.py", line 30, in main
    amd.download()
  File "/Users/Downloads/ard-mediathek-master/ard_media_downloader.py", line 50, in download
    video_url = self.get_video_url()
  File "/Users/Downloads/ard-mediathek-master/ard_media_downloader.py", line 79, in get_video_url
    raise RuntimeError("The document id could not be found.")
RuntimeError: The document id could not be found.

Do you have any solution?

Thank you so much for your work!!

**Comment by czhu** [comment]
the url needs to be quoted like "url"

**Comment by steffenschroeder** [comment]
The URL does not contain a `documentId`, hence the video cannot be found.
If you start with http://mediathek.daserste.de/ and search there, you'll get http://mediathek.daserste.de/Sportschau/Stark-am-Kreis-Spanien-in-Kleins-Gegner/Video?bcastId=53524&documentId=59625378 which should work for you.
