### ISSUE TITLE
error: InvalidSchema: No connection adapters were found for http:https...

### ISSUE THREAD

**Issue by rriemann** [Bouni/ard-mediathek#5]
Hallo,

das Skript hat irgendein Problem bei mir. Vielleicht ist es einfacher wenn das Skript einfach nur den Pfad via STDOUT ausgibt, der dann mit curl oder wget verwendet werden kann.

```
ard-mediathek.py http://www.ardmediathek.de/tv/Tatort/Tatort-Der-Irre-Iwan/MDR-Fernsehen/Video\?bcastId\=15757542\&documentId\=49446920
Since no filename was given the default value 'video.mp4' will be used.
Traceback (most recent call last):
  File "/home/rriemann/bin/ard-mediathek.py", line 165, in <module>
    main(sys.argv)
  File "/home/rriemann/bin/ard-mediathek.py", line 159, in main
    amd.download()
  File "/home/rriemann/bin/ard-mediathek.py", line 82, in download
    r = requests.get(video, stream=True)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 703, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'http:https://odmdr-a.akamaihd.net/mp4dyn/2/FCMS-272a6a9b-9f44-45ba-a7db-93b5e3e2faa1-02faac9018d3_27.mp4'
```

**Comment by Bouni** [comment]
Hi, hab schon länger nicht mehr drauf geschaut ob das Script noch tut :-/
Vielleich bau ich die Tage mal einen commandline switch ein der das mit dem STDOUT ermöglicht, ist ne gute Idee!

**Comment by Bouni** [comment]
Ok, ist gefixt!

Wichtig ist das die URL in "" ist, sonst kommt auf der commandline das & in die Quere!
Also `ard-mediathek.py "http://www.ardmediathek.de/tv/Tatort/Tatort-Der-Irre-Iwan/MDR-Fernsehen/Video?bcastId=15757542&documentId=49446920"`
