### ISSUE TITLE
Script crashes with file name switch provided

### ISSUE THREAD

**Issue by rriemann** [Bouni/ard-mediathek#9]
So I added the switch `-f epsiode02.mp3` and go this error:

```
Destination path '' does not exist. Try to create it ...
Traceback (most recent call last):
  File "/home/rriemann/bin/ard-mediathek.py", line 106, in set_filename
    os.makedirs(os.path.dirname(filename))
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rriemann/bin/ard-mediathek.py", line 165, in <module>
    main(sys.argv)
  File "/home/rriemann/bin/ard-mediathek.py", line 157, in main
    amd.set_filename(args.filename)
  File "/home/rriemann/bin/ard-mediathek.py", line 108, in set_filename
    raise RuntimeError("The destination path could not be built. Aborting.")
RuntimeError: The destination path could not be built. Aborting.
```

**Comment by Bouni** [comment]
Fixed by #11
